credentials:
  usernames:
    korkork:
      email: kwaomavis@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Mavis Kwao 
      password: "1234" # Will be hashed automatically
    prockson:
      email: korkork Solution
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: korkork Solution
      password: "Agent0047" # Will be hashed automatically
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
pre-authorized:
  emails:
  - kwaomavis@gmail.com